spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: catalog
    password: catalog
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080
